/**
 * ADVANCED METADATA GENERATOR v3.0
 * AI-powered metadata generation for maximum SEO
 * Generates optimized meta tags for all content types and search engines
 */

interface MetadataConfig {
  title: string;
  description: string;
  keywords: string[];
  url: string;
  image?: string;
  author?: string;
  datePublished?: string;
  dateModified?: string;
  category?: string;
  contentType?: 'article' | 'product' | 'recipe' | 'video' | 'tool' | 'news';
  language?: string;
  robots?: string;
}

interface GeneratedMetadata {
  htmlHead: string;
  ogTags: Record<string, string>;
  twitterTags: Record<string, string>;
  additionalMeta: Record<string, string>;
}

export class AdvancedMetadataGenerator {
  /**
   * Generate comprehensive metadata for any page
   */
  static generateMetadata(config: MetadataConfig): GeneratedMetadata {
    const ogTags = this.generateOpenGraphTags(config);
    const twitterTags = this.generateTwitterCardTags(config);
    const additionalMeta = this.generateAdditionalMeta(config);
    const htmlHead = this.generateHTMLHead(config, ogTags, twitterTags, additionalMeta);

    return {
      htmlHead,
      ogTags,
      twitterTags,
      additionalMeta,
    };
  }

  /**
   * Generate Open Graph tags for social media
   */
  private static generateOpenGraphTags(config: MetadataConfig): Record<string, string> {
    const tags: Record<string, string> = {
      'og:title': this.optimizeTitleForOG(config.title),
      'og:description': this.optimizeDescriptionForOG(config.description),
      'og:type': this.determineOGType(config.contentType),
      'og:url': config.url,
      'og:site_name': 'ISHU — Indian StudentHub University',
      'og:locale': this.getLocale(config.language),
      'og:locale:alternate': this.getAlternateLocales(config.language),
    };

    if (config.image) {
      tags['og:image'] = config.image;
      tags['og:image:width'] = '1200';
      tags['og:image:height'] = '630';
      tags['og:image:alt'] = config.title;
      tags['og:image:type'] = 'image/png';
    }

    if (config.datePublished) {
      tags['article:published_time'] = config.datePublished;
    }

    if (config.dateModified) {
      tags['article:modified_time'] = config.dateModified;
    }

    if (config.author) {
      tags['article:author'] = config.author;
    }

    if (config.category) {
      tags['article:section'] = config.category;
    }

    // Add keywords as article:tag
    if (config.keywords && config.keywords.length > 0) {
      tags['article:tag'] = config.keywords.slice(0, 5).join(', ');
    }

    return tags;
  }

  /**
   * Generate Twitter Card tags
   */
  private static generateTwitterCardTags(config: MetadataConfig): Record<string, string> {
    return {
      'twitter:card': 'summary_large_image',
      'twitter:title': this.optimizeTitleForTwitter(config.title),
      'twitter:description': this.optimizeDescriptionForTwitter(config.description),
      'twitter:image': config.image || 'https://ishu.fun/og-image.png',
      'twitter:image:alt': config.title,
      'twitter:site': '@ishufun',
      'twitter:creator': '@ishufun',
      'twitter:domain': 'ishu.fun',
      'twitter:url': config.url,
    };
  }

  /**
   * Generate additional meta tags
   */
  private static generateAdditionalMeta(config: MetadataConfig): Record<string, string> {
    return {
      'charset': 'UTF-8',
      'viewport': 'width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes',
      'description': config.description,
      'keywords': config.keywords.join(', '),
      'author': config.author || 'ISHU Team',
      'robots': config.robots || 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
      'googlebot': 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
      'bingbot': 'index, follow',
      'mobile-web-app-capable': 'yes',
      'apple-mobile-web-app-capable': 'yes',
      'apple-mobile-web-app-status-bar-style': 'black-translucent',
      'theme-color': '#1a1a2e',
      'color-scheme': 'light dark',
    };
  }

  /**
   * Generate complete HTML head section
   */
  private static generateHTMLHead(
    config: MetadataConfig,
    ogTags: Record<string, string>,
    twitterTags: Record<string, string>,
    additionalMeta: Record<string, string>
  ): string {
    let html = `
<!-- SEO Meta Tags - Generated by AdvancedMetadataGenerator -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">

<!-- Primary Meta Tags -->
<title>${this.escapeHTML(config.title)}</title>
<meta name="title" content="${this.escapeHTML(config.title)}">
<meta name="description" content="${this.escapeHTML(config.description)}">
<meta name="keywords" content="${this.escapeHTML(config.keywords.join(', '))}">
<meta name="author" content="${config.author || 'ISHU Team'}">
<link rel="canonical" href="${config.url}">

<!-- Robots & Indexing -->
<meta name="robots" content="${additionalMeta['robots']}">
<meta name="googlebot" content="${additionalMeta['googlebot']}">
<meta name="bingbot" content="${additionalMeta['bingbot']}">

<!-- Language & Geo Targeting -->
<meta http-equiv="content-language" content="${config.language || 'en-IN'}">
<meta name="language" content="${config.language || 'en-IN, hi-IN'}">
<meta name="geo.region" content="IN">
<meta name="geo.placename" content="India">
<meta name="ICBM" content="20.5937, 78.9629">

<!-- Open Graph / Facebook -->
    `;

    Object.entries(ogTags).forEach(([key, value]) => {
      html += `<meta property="${key}" content="${this.escapeHTML(value)}">\n`;
    });

    html += `
<!-- Twitter Card -->
    `;

    Object.entries(twitterTags).forEach(([key, value]) => {
      html += `<meta name="${key}" content="${this.escapeHTML(value)}">\n`;
    });

    html += `
<!-- Device & App Meta Tags -->
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="#1a1a2e">
<meta name="color-scheme" content="light dark">

<!-- IE Compatibility -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Icons -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="shortcut icon" href="/favicon.ico">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#1a1a2e">

<!-- Web App Manifest -->
<link rel="manifest" href="/manifest.json">

<!-- Preconnect & DNS Prefetch for Performance -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="dns-prefetch" href="https://www.google-analytics.com">
<link rel="dns-prefetch" href="https://www.googletagmanager.com">

<!-- Verification Tags -->
<meta name="google-site-verification" content="YOUR_GOOGLE_CODE">
<meta name="msvalidate.01" content="YOUR_BING_CODE">

<!-- Hreflang for Multilingual Pages -->
<link rel="alternate" hreflang="en-IN" href="https://ishu.fun/en">
<link rel="alternate" hreflang="hi-IN" href="https://ishu.fun/hi">
<link rel="alternate" hreflang="x-default" href="https://ishu.fun">
    `;

    return html;
  }

  /**
   * Optimize title for Open Graph
   */
  private static optimizeTitleForOG(title: string): string {
    // Ensure it's under 60 chars for OG
    return title.substring(0, 60);
  }

  /**
   * Optimize description for Open Graph
   */
  private static optimizeDescriptionForOG(description: string): string {
    // Ensure it's under 160 chars
    return description.substring(0, 160);
  }

  /**
   * Optimize title for Twitter
   */
  private static optimizeTitleForTwitter(title: string): string {
    // Twitter has 70 char limit
    return title.substring(0, 70);
  }

  /**
   * Optimize description for Twitter
   */
  private static optimizeDescriptionForTwitter(description: string): string {
    // Twitter has 200 char limit
    return description.substring(0, 200);
  }

  /**
   * Determine Open Graph content type
   */
  private static determineOGType(contentType?: string): string {
    const typeMap: Record<string, string> = {
      article: 'article',
      product: 'product',
      recipe: 'recipe',
      video: 'video.other',
      tool: 'website',
      news: 'article',
    };

    return typeMap[contentType || 'website'] || 'website';
  }

  /**
   * Get locale code
   */
  private static getLocale(language?: string): string {
    const localeMap: Record<string, string> = {
      en: 'en_IN',
      hi: 'hi_IN',
      ta: 'ta_IN',
      te: 'te_IN',
      bn: 'bn_IN',
      mr: 'mr_IN',
      gu: 'gu_IN',
      kn: 'kn_IN',
      ml: 'ml_IN',
      pa: 'pa_IN',
      ur: 'ur_IN',
      or: 'or_IN',
    };

    return localeMap[language || 'en'] || 'en_IN';
  }

  /**
   * Get alternate locales
   */
  private static getAlternateLocales(language?: string): string {
    const alternates = [
      'hi_IN',
      'ta_IN',
      'te_IN',
      'bn_IN',
      'mr_IN',
      'gu_IN',
      'kn_IN',
      'ml_IN',
      'pa_IN',
      'ur_IN',
      'or_IN',
    ];

    const current = this.getLocale(language);
    return alternates.filter((l) => l !== current).join(', ');
  }

  /**
   * Escape HTML in metadata
   */
  private static escapeHTML(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };

    return text.replace(/[&<>"']/g, (char) => map[char]);
  }

  /**
   * Generate metadata for product pages
   */
  static generateProductMetadata(product: {
    name: string;
    description: string;
    price: string;
    image: string;
    rating?: number;
    reviewCount?: number;
    url: string;
  }): GeneratedMetadata {
    const keywords = [
      `${product.name}`,
      `buy ${product.name}`,
      `${product.name} price`,
      `${product.name} online`,
      `best ${product.name}`,
    ];

    return this.generateMetadata({
      title: `${product.name} | Free Online | ISHU`,
      description: `${product.description}. Price: ${product.price}. Get instant access now.`,
      keywords,
      url: product.url,
      image: product.image,
      contentType: 'product',
    });
  }

  /**
   * Generate metadata for articles
   */
  static generateArticleMetadata(article: {
    title: string;
    excerpt: string;
    content: string;
    author: string;
    datePublished: string;
    dateModified?: string;
    image: string;
    url: string;
    category: string;
    tags: string[];
  }): GeneratedMetadata {
    const keywords = [article.category, ...article.tags.slice(0, 5)];

    return this.generateMetadata({
      title: `${article.title} | Latest News | ISHU`,
      description: article.excerpt.substring(0, 160),
      keywords,
      url: article.url,
      image: article.image,
      author: article.author,
      datePublished: article.datePublished,
      dateModified: article.dateModified,
      category: article.category,
      contentType: 'article',
    });
  }

  /**
   * Generate metadata for tools
   */
  static generateToolMetadata(tool: {
    name: string;
    description: string;
    features: string[];
    url: string;
    image: string;
  }): GeneratedMetadata {
    const keywords = [
      `${tool.name} free`,
      `${tool.name} online`,
      `best ${tool.name}`,
      `${tool.name} tools`,
      ...tool.features.slice(0, 3),
    ];

    return this.generateMetadata({
      title: `Free ${tool.name} Online | ISHU`,
      description: `${tool.description}. Use ${tool.name} free online without signup or download.`,
      keywords,
      url: tool.url,
      image: tool.image,
      contentType: 'tool',
    });
  }

  /**
   * Generate metadata for news
   */
  static generateNewsMetadata(news: {
    headline: string;
    summary: string;
    image: string;
    url: string;
    datePublished: string;
    source: string;
  }): GeneratedMetadata {
    const keywords = ['news India', 'latest news', news.headline.split(' ').slice(0, 3).join(' ')];

    return this.generateMetadata({
      title: `${news.headline} | ISHU News`,
      description: news.summary.substring(0, 160),
      keywords,
      url: news.url,
      image: news.image,
      author: news.source,
      datePublished: news.datePublished,
      contentType: 'news',
    });
  }

  /**
   * Batch generate metadata for multiple pages
   */
  static batchGenerateMetadata(
    configs: MetadataConfig[]
  ): Array<{ config: MetadataConfig; metadata: GeneratedMetadata }> {
    return configs.map((config) => ({
      config,
      metadata: this.generateMetadata(config),
    }));
  }

  /**
   * Get SEO score based on metadata completeness
   */
  static calculateSEOScore(config: MetadataConfig): { score: number; issues: string[] } {
    const issues: string[] = [];
    let score = 0;

    // Title check (100 points)
    if (config.title && config.title.length > 30 && config.title.length < 60) {
      score += 20;
    } else {
      issues.push('Title should be 30-60 characters');
    }

    // Description check (80 points)
    if (config.description && config.description.length > 120 && config.description.length < 160) {
      score += 20;
    } else {
      issues.push('Description should be 120-160 characters');
    }

    // Keywords check (60 points)
    if (config.keywords && config.keywords.length >= 5 && config.keywords.length <= 10) {
      score += 15;
    } else {
      issues.push('Should have 5-10 keywords');
    }

    // URL check (40 points)
    if (config.url && config.url.length < 100) {
      score += 15;
    } else {
      issues.push('URL too long');
    }

    // Image check (40 points)
    if (config.image) {
      score += 15;
    } else {
      issues.push('Add OG image for social sharing');
    }

    // Meta data completeness (40 points)
    if (config.datePublished) score += 5;
    if (config.author) score += 5;
    if (config.category) score += 5;
    if (config.contentType) score += 5;

    return {
      score: Math.min(100, score),
      issues,
    };
  }
}

export const advancedMetadataGenerator = new AdvancedMetadataGenerator();
